# Generated by Django 3.2.8 on 2021-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='name')),
                ('prod_image', models.ImageField(upload_to='')),
                ('prod_decription', models.TextField()),
            ],
        ),
    ]
