# Generated by Django 3.2.9 on 2021-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_image',
            field=models.ImageField(upload_to='market/static/images'),
        ),
    ]
